### ISSUE TITLE
I got error when i build!

### ISSUE THREAD

**Issue by nvtinh368** [vicnetto/SSL-TLS-Proxy#1]
Hello thanks for the great project. Can you provide specific instructions on which libraries you have installed and what environment you are running on? I got an error when compiling according to the instructions and the issue was related to openssl thank you

**Comment by vicnetto** [comment]
Hi @nvtinh368,

Thank you for your feedback! I'm glad to hear that you're interested in the project.

Could you please share the command and the log with me?

I followed the instructions and didn't encounter any issues running it. I'm using EndeavourOS (an Arch-based distro) with the 6.9.2-arch1-1 kernel.

**Comment by nvtinh368** [comment]
What version of openssl are you using? Currently I have successfully built on Ubuntu 20.04 but I have the problem of failed handshakes. despite installing the certificate I created myself on firefox it would be good if you have complete instructions on ubuntu. Thanks

**Comment by vicnetto** [comment]
I will try to run it on Ubuntu and will get back to you.

My version of OpenSSL:
```text
OpenSSL 3.3.0 9 Apr 2024 (Library: OpenSSL 3.3.0 9 Apr 2024)
```

You didn't send the error logs. Could you please send them to me? 

Did you provide the correct certificate to the application? Does it work if you generate the certificates within the application, as described in the README?

**Comment by nvtinh368** [comment]
i installed another version of openssl. and maybe that's why it doesn't work. I will try your current version.
I did exactly the same as in your instructions

**Comment by nvtinh368** [comment]
![Uploading Screenshot 2024-06-06 132944.png…]()

**Comment by nvtinh368** [comment]
I got it working. it works fine on ubuntu 22.04.
But it's so slow it seems it's not used multithreading. I will code and update a new version for this project.

**Comment by nvtinh368** [comment]
I'm still not sure why some websites cannot handshake when changing sni:
for example: https://icanhazip.com/

**Comment by nvtinh368** [comment]
![image](https://github.com/vicnetto/SNI-Changer-using-MitM-Proxy/assets/71061944/35cef039-a168-474d-8d84-da15907e725f)

**Comment by cholezth** [comment]
That's normal. Some websites will not accept a fake SNI because some of them actually need the right SNI because they use virtual hosting and the web server holds several different certificates for the hosted websites. That's actually the prime purpose why SNI was invented.

**Comment by vicnetto** [comment]
> I got it working. it works fine on ubuntu 22.04. But it's so slow it seems it's not used multithreading. I will code and update a new version for this project.

Yes, currently there is no multithreading, so connections can be slower than usual. Adding it would be a great addition to the project.
